### ISSUE TITLE
autokeras

### ISSUE THREAD

**Issue by itsergiu** [Virtual-Machines/Anaconda-VirtualBox#2]
Anaconda does not include autokeras.
Could you please install it?

https://autokeras.com/

**Comment by DavidGarciaPrados** [comment]
Hi

Auto-Keras comes into conflict with current Anaconda and is a very specific package.
For that reason, **I have buit a special machine for you** that contains Auto-Keras and all its dependencies, Spyder and Jupyter Notebook.

I have added this to README:
**New!** dedicated to [**@itsergiu**](https://github.com/itsergiu). If you want an Auto-Keras machine you can get it here: [**DOWNLOAD**](https://github.com/Virtual-Machines/Anaconda-VirtualBox/releases/download/latest/Autokeras.ova)

**Comment by DavidGarciaPrados** [comment]
> Anaconda does not include autokeras.
> Could you please install it?
> 
> https://autokeras.com/

@itsergiu Are you happy with the Auto-Keras virtual machine?

**Comment by itsergiu** [comment]
I am happy. 👍  It works fine! Thank you!

**Comment by DavidGarciaPrados** [comment]
> I am happy.  It works fine! Thank you!

You are welcome
