### ISSUE TITLE
It can't be updated

### ISSUE THREAD

**Issue by renejara-infotec** [Virtual-Machines/Anaconda-VirtualBox#4]
It can not be updated using the command:
conda update --all

Neither is possible to install the Rstudio through Anaconda or run a R notebook in a R enviroment

**Comment by DavidGarciaPrados** [comment]
Hi

> It can not be updated using the command: conda update --all
Run "conda install anaconda" to solve the problem
Run "conda update conda anaconda" to update

> Neither is possible to install the Rstudio through Anaconda or run a R notebook in a R enviroment
You followed these tutorials?
https://docs.anaconda.com/anaconda/navigator/tutorials/r-lang/
https://docs.anaconda.com/anaconda/navigator/tutorials/create-r-environment/
